import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import localFont from "next/font/local";
import { ToastContainer, toast } from 'react-toastify';

const sfCollegiate = localFont({
  src: [
    {
      path: "../Utils/Fonts/SF_Collegiate_Solid.ttf",
      weight: "400",
      style: "normal",
    },
    
  ],
  variable: "--font-sf-collegiate",
});

export const metadata = {
  title: "Airdrop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sfCollegiate.variable} relative`}>
        <div className="fixed top-0 left-0 right-0 z-50">
          <ToastContainer/>
          <Navbar toast={toast}/>
        </div>
        {children}
      </body>
    </html>
  );
}
